# Generated by Django 3.1.3 on 2020-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.TextField(default=0)),
                ('comment_txt', models.TextField(default='-', max_length=100)),
                ('pname', models.TextField(default='-', max_length=100)),
                ('ctype', models.IntegerField(default=0)),
                ('date', models.TextField(default='-', max_length=100)),
                ('time', models.TextField(default='-', max_length=100)),
            ],
        ),
    ]
