# Generated by Django 3.1.3 on 2020-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pemail',
            field=models.TextField(default='-', max_length=300),
        ),
    ]
