# Generated by Django 3.1.3 on 2020-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201204_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Newsletters',
            field=models.TextField(default='-', max_length=300),
        ),
    ]
