# Generated by Django 3.1.3 on 2020-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitesetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='-', max_length=100)),
                ('email', models.CharField(default='-', max_length=100)),
                ('insta', models.CharField(default='-', max_length=100)),
                ('tell', models.CharField(default='-', max_length=100)),
                ('address', models.CharField(default='-', max_length=100)),
                ('logo', models.TextField(default='-', max_length=100)),
                ('logourl', models.TextField(default='-', max_length=100)),
                ('banner1', models.TextField(default='-', max_length=100)),
                ('banner1url', models.TextField(default='-', max_length=100)),
                ('banner2', models.TextField(default='-', max_length=100)),
                ('banner2url', models.TextField(default='-', max_length=100)),
                ('banner3', models.TextField(default='-', max_length=100)),
                ('banner3url', models.TextField(default='-', max_length=100)),
                ('biotext', models.TextField(max_length=300)),
            ],
        ),
    ]
