# Generated by Django 3.1.3 on 2020-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_auto_20201206_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_txt',
            field=models.TextField(default='-', max_length=500),
        ),
    ]
