# Generated by Django 3.1.3 on 2020-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=100)),
                ('time', models.CharField(default='-', max_length=100)),
                ('date', models.CharField(default='-', max_length=100)),
                ('short_txt', models.TextField(default='-', max_length=100)),
                ('text', models.TextField(default='-', max_length=300)),
                ('pic', models.TextField(default='-', max_length=100)),
                ('picurl', models.TextField(default='-', max_length=100)),
                ('writer', models.TextField(default='-', max_length=100)),
                ('show', models.IntegerField(default=0)),
                ('catid', models.IntegerField(default=0)),
                ('catname', models.CharField(default='-', max_length=40)),
                ('subcatname', models.CharField(default='-', max_length=40)),
                ('subcatid', models.IntegerField(default=0)),
                ('ocatid', models.IntegerField(default=0)),
                ('rand', models.IntegerField(default=0)),
            ],
        ),
    ]
