# Generated by Django 3.1.3 on 2020-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201121_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.IntegerField(),
        ),
    ]
