# Generated by Django 3.1.3 on 2020-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201125_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='-', max_length=3000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
