# Generated by Django 3.1.3 on 2020-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201202_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
