# Generated by Django 3.1.3 on 2020-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201204_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic10',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic2',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic3',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic4',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic5',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic6',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic7',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic8',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='pic9',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl10',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl2',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl3',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl4',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl5',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl6',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl7',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl8',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl9',
            field=models.TextField(default='-', max_length=100),
        ),
    ]
